In [7]:
# 1=exited 0=not exited

Importing the libraries

In [8]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [9]:
tf.__version__

'2.11.0'

# Data Pre-processing

Importing the data set

In [11]:
dataset=pd.read_csv('Churn_Modelling.csv ')
X=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [12]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [13]:
print(y)

[1 0 1 ... 1 1 0]


Encoding Categorical data

In [16]:
# Label Encoding of Gender
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

In [17]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [18]:
# One hot encoding the "Geography column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [19]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Splitting the dataset into the training set and test set

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

Feature Scaling

In [21]:
# feature scaling is compulsory for deep learning
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

# Building the ANN

Initialize the ANN

In [22]:
ann= tf.keras.models.Sequential()

 Adding the input layer and the first hidden layer

In [23]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding Second hidden layer

In [24]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 

Adding the output layer

In [25]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Training the ANN

Compiling the ANN

In [26]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

Training the ANN on the training set

In [27]:
ann.fit(X_train, y_train, batch_size= 32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5438 - accuracy: 0.7707
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4772 - accuracy: 0.7964
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4514 - accuracy: 0.7972
Epoch 4/100
250/250 [==============================] - 0s 987us/step - loss: 0.4354 - accuracy: 0.8008
Epoch 5/100
250/250 [==============================] - 0s 989us/step - loss: 0.4238 - accuracy: 0.8060
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4134 - accuracy: 0.8120
Epoch 7/100
250/250 [==============================] - 0s 996us/step - loss: 0.4020 - accuracy: 0.8224
Epoch 8/100
250/250 [==============================] - 0s 983us/step - loss: 0.3914 - accuracy: 0.8313
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3815 - accuracy: 0.8399
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3747 

250/250 [==============================] - 0s 958us/step - loss: 0.3332 - accuracy: 0.8644
Epoch 81/100
250/250 [==============================] - 0s 956us/step - loss: 0.3336 - accuracy: 0.8625
Epoch 82/100
250/250 [==============================] - 0s 959us/step - loss: 0.3337 - accuracy: 0.8637
Epoch 83/100
250/250 [==============================] - 0s 985us/step - loss: 0.3331 - accuracy: 0.8652
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3335 - accuracy: 0.8634
Epoch 85/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3334 - accuracy: 0.8634
Epoch 86/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3331 - accuracy: 0.8635
Epoch 87/100
250/250 [==============================] - 0s 980us/step - loss: 0.3331 - accuracy: 0.8629
Epoch 88/100
250/250 [==============================] - 0s 976us/step - loss: 0.3332 - accuracy: 0.8625
Epoch 89/100
250/250 [==============================] - 0s 977us/step - loss: 0.332

# Making the prediction and evaluating the model

 Predicting the result of a single observation

In [32]:
print(ann.predict(sc.transform([[1,0,0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
print(ann.predict(sc.transform([[1,0,0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))>0.5)

1/1 [==============================] - 0s 19ms/step
[[0.03507141]]
1/1 [==============================] - 0s 17ms/step
[[False]]


Predicting the test set results

In [33]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 804us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Making confusion matrix

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1518   77]
 [ 196  209]]


0.8635